name: Publish package
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Git configuration
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions"

      - name: Setup python environment
        run: |
          pip3 install -r requirements.txt

      - name: Set release version
        run: |
          echo "NEW_VERSION=$(tools/update-version.py release)" >> $GITHUB_ENV

      - name: Build
        run: |
          rm -rf code/wrappers/python/src/spreader.egg-info 
          mkdir -p dist/tmp 
          python3 setup.py egg_info --egg-base dist/tmp sdist 

      - name: Update changelog
        uses: superfaceai/release-changelog-action@v2
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ env.NEW_VERSION }}
          operation: release

      - name: Commit CHANGELOG.md and package.json changes and create tag
        run: |
          git add "setup.py"
          git add "CHANGELOG.md"
          git commit -m "chore: release ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}

      - name: Set next dev version
        run: |
          NEXT_VERSION=$(tools/update-version.py nextpatch)
          git add "setup.py"   
          git commit -m "chore: bump version to $NEXT_VERSION"

      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin && git push --tags

      - name: Publish
        run: twine upload --non-interactive dist/eg.spreader-${{ env.NEW_VERSION }}.tar.gz 
        env:
          TWINE_REPOSITORY: testpypi
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_ACCESS_TOKEN }}

      - id: get-changelog
        name: Get version changelog
        uses: superfaceai/release-changelog-action@v2
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ env.NEW_VERSION }}
          operation: read

      - name: Update GitHub release documentation
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}
          body: ${{ steps.get-changelog.outputs.changelog }}
          files: |
            dist/eg.spreader-${{ env.NEW_VERSION }}.tar.gz
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

