name: Test

on: 
  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'
      - 'Acknowledgments.md'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.github/workflows/publish.yml'

jobs:
  matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy-3.8"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64

      - name: Install Nox
        run: pip install Nox

      - name: Test
        run: nox --sessions test --force-python ${{ steps.setup-python.outputs.python-path }}

